### PR TITLE
COOL2

### PR DESCRIPTION
**Pull request by feqifei**

### CODE REVIEW

**Comment by feqifei** [comment]
I'm sorry but I'm not able to clean the registry of my repo. Those files are deleted but they remain in the history, I spent the last 4 hours but I really don't know how to remove them. Please let me know if we can proceed anyway

**Comment by feqifei** [comment]
I tried to pull a request through another github user but when I fork the repo several json and sig files are created into the registry folder.
So, I'm not able to find a way to avoid files that existed into the registry folder of CF repo, please let me know if we can proceed with this request.
Thanks

**Comment by admin-cf-1** [comment]
Cannot proceed with this request - please open a new PR to proceed.

**Comment by feqifei** [comment]
> Cannot proceed with this request - please open a new PR to proceed.

Hi, when I fork CF repo all json and sig located in the registry folder are copied in my fork.
The only step I do is to delete them from my repo.
In which other way I have to operate to avoid it?

**Comment by admin-cf-1** [comment]
Try not deleting them, that way the only diff would be two files you add.

**Comment by feqifei** [comment]
> Try not deleting them, that way the only diff would be two files you add.

ok, thank you, I'll try

**Pull request closed without merging**
