### PR TITLE
EVER

### PR DESCRIPTION
**Pull request by keynobase**
URL updated

### CODE REVIEW

**Comment by keynobase** [comment]
Please, can you write this 2 files for EVER Pool ? I dont know how solve this error

**Comment by keynobase** [comment]
Now I only has one branch, please can you put thi 2 files ?

**Comment by admin-cf-1** [comment]
it seem your PR is still touching **4 files** - this will trip the automated checks - please make sure you follow proper procedures. See Wiki and documentation for help.

**Comment by keynobase** [comment]
Please can you close it ?

**Comment by keynobase** [comment]
I ve deleted all files.. yo can close it ?

**Pull request closed without merging**
