### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 1PCT**

### CODE REVIEW

**Comment by 1PCT** [comment]
When accept?

**Comment by 1procentpool** [comment]
DO NOT merge this pull request!! This is a copy-cat, trying to confuse stakers and leech off the real 1 Percent Pool. This is exactly what I warned about, and why I tried to reserve all the tickers. @admin-cf-1

**Comment by 1PCT** [comment]
> DO NOT merge this pull request!! This is a copy-cat, trying to confuse stakers and leech off the real 1 Percent Pool. This is exactly what I warned about, and why I tried to reserve all the tickers. @admin-cf-1

First it was a joke! But why not accept? If i change the website and info etc i can use 1PCTA 
There is nothing wrong with this!  Don't claim 1PCT*

**Comment by admin-cf-2** [comment]
> DO NOT merge this pull request!! This is a copy-cat, trying to confuse stakers and leech off the real 1 Percent Pool. This is exactly what I warned about, and why I tried to reserve all the tickers. @admin-cf-1

FYI: Only the pool owner can generate a valid signature file to proof that he is authorized to change the data. That is why we always require a JSON file and a signature per pull request.

**Pull request closed without merging**
