### PR TITLE
adding new staking pool validators.online (VO)

### PR DESCRIPTION
**Pull request by sweetpotatoz**
adding new staking pool validators.online (VO)

### CODE REVIEW

**Comment by admin-cf-1** [comment]
**Please note that the automated checks are failing.** Passing the automated tests is mandatory. To get more details about why it is failing, click on ‘details’ in the check section and scroll all the way down to the bottom of the resulting page.

**Comment by sweetpotatoz** [comment]
update ticket from VO to VOSP since ticker require minimum 3 characters

**Comment by admin-cf-1** [comment]
There still appear to be an issue with the signature

**Comment by sweetpotatoz** [comment]
git push locally instead from stake pool VPS.  so copied the content of .sig file and didnt check the shasum.  SCP from VPS now, and check shasum for .sig file.  The files should be fine now.  Thank you!

**Pull request merged**
