### PR TITLE
Boom

### PR DESCRIPTION
**Pull request by boomstake**
json formatting fixed and description added.

### CODE REVIEW

**Comment by boomstake** [comment]
Hi, do I make a new pull request in the same branch or does it need to be a new branch ?

**Comment by admin-cf-1** [comment]
You should be able to commit to this branch.

**Comment by admin-cf-1** [comment]
I would suggest asking for help in the [Telegram group](https://t.me/CardanoStakePoolWorkgroup) - there might have been others that have better experience or might be able to point you in the right direction!

**Comment by admin-cf-1** [comment]
Consider if it might be an encoding issue? Windows has been causing issues when it comes to file encoding.

Potentially similar issues touching to Signature: 
- https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/165#issuecomment-564840151 (solved by submitting through web IDE) 
- https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/30#issuecomment-564018421  (encoding) 

For even further support I would suggest reaching out to the [TG Pool Operator group](https://t.me/CardanoStakePoolWorkgroup)

**Comment by boomstake** [comment]
Hi admin,  
The file states, that all checks have passed.

**Pull request merged**
