### PR TITLE
ATADA New Stakepool in Austria - Please add

### PR DESCRIPTION
**Pull request by gitmachtl**
New Austria Stakepool

### CODE REVIEW

**Comment by cinnl** [comment]
You have to use double quotes in the json and do a new sig file. that should solve your issue.

**Comment by gitmachtl** [comment]
> You have to use double quotes in the json and do a new sig file. that should solve your issue.

ok thanks, just commited again. now with double-quotes in the json file. 

so the example on https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md is wrong?

**Comment by cinnl** [comment]
> > You have to use double quotes in the json and do a new sig file. that should solve your issue.
> 
> ok thanks, just commited again. now with double-quotes in the json file.
> 
> so the example on https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md is wrong?

yes, every resource I read had single quotes. They should update the documentation.

**Comment by gitmachtl** [comment]
Just changed the TICKER name and added some description, THANKS!!!

**Comment by gitmachtl** [comment]
Hi, do you have an idea how long it will take to merge my new stakepool into the master branch? Can't wait to test it out. I know i'am a little late in the game.

**Pull request merged**
