### PR TITLE
PEARL Stake Pool

### PR DESCRIPTION
**Pull request by hardc0l2e**
Hi,

We're requesting to add our Stake Pool in your current listing.

thank you

-=ronald

### CODE REVIEW

**Comment by hardc0l2e** [comment]
oh ok thank you.

**Comment by hardc0l2e** [comment]
We will send a request of approval to legal@cardanofoundation.org, as we have seen similar domain like cardanocanada.com and cardanohawaii.com registered their respective stake pools.

**Comment by admin-cf-2** [comment]
> We will send a request of approval to [legal@cardanofoundation.org](mailto:legal@cardanofoundation.org), as we have seen similar domain like cardanocanada.com and cardanohawaii.com registered their respective stake pools.

No need to contact legal because of this domain, it's not in line with the trademark policy. They were asked to change the addresses. I'm really sorry.

**Comment by hardc0l2e** [comment]
I already updated the details in the forked instance of .json file from cardano-philippines.com to pearlstaking.com...now what to do to complete the registration?

**Pull request closed without merging**
