### PR TITLE
VOLCY

### PR DESCRIPTION
**Pull request by gvolcy**

### CODE REVIEW

**Comment by gvolcy** [comment]
plzz i need to know what I'm doing wrong

**Comment by afrca** [comment]
> plzz i need to know what I'm doing wrong

you are missing a , in your json file on the ticker line

**Comment by gvolcy** [comment]
> > plzz i need to know what I'm doing wrong
> 
> you are missing a , in your json file on the ticker line
>i don't understand what's wrong with my ticker line do i have to redo my json file

**Comment by afrca** [comment]
> > > plzz i need to know what I'm doing wrong
> > 
> > 
> > you are missing a , in your json file on the ticker line
> > i don't understand what's wrong with my ticker line do i have to redo my json file

You need a comma at the very end of the line, so yes you will need to redo the json file with the correct syntax and sign it again

**Comment by gvolcy** [comment]
> > > > plzz i need to know what I'm doing wrong
> > > 
> > > 
> > > you are missing a , in your json file on the ticker line
> > > i don't understand what's wrong with my ticker line do i have to redo my json file
> 
> You need a comma at the very end of the line, so yes you will need to redo the json file with the correct syntax and sign it again

thank you soo much

**Pull request closed without merging**
