### PR TITLE
Please allow registration of BKND2

### PR DESCRIPTION
**Pull request by Gertjan-stakingpoolholder**

### CODE REVIEW

**Comment by Gertjan-stakingpoolholder** [comment]
Dear CF,

 

I am not sure if I understand correctly.

 

Is it not allowed to use the word cardano in the domainname of my website?

 

Please let me know.

 

With kind regards,

Gertjan

**Comment by Gertjan-stakingpoolholder** [comment]
I made the change.

**Comment by sdalmeida** [comment]
hi @Gertjan-stakingpoolholder 
a PR can only have 2 file modified, looking at you PR, you modified 4 files (not sure if those pools are owned by you or not).
If you need to make changes to multiple pools at once, I would recommend splitting each pool change to a PR.

**Comment by Gertjan-stakingpoolholder** [comment]
Hi,

 

Yes, the pool is owned by me. Could you please register the pool? The last two files are the correct ones. See below:

 4  registry/ed25519_pk1de4kup8ad9zqjeucfys5u78jkrdv7yw52y4un8fyndyaumx2rj4ss5dkwm.json 

@@ -1,8 +1,8 @@
{
  "owner": "ed25519_pk1de4kup8ad9zqjeucfys5u78jkrdv7yw52y4un8fyndyaumx2rj4ss5dkwm",
  "name": "BeKind2",
  "description": "The supportive staking-pool operated by Gertjan Smit",
  "description": "Supportive stakepool operated by Gertjan Smit",
  "ticker": "BKND2",
  "homepage": "https://cardanostakingpool.online",
  "homepage": "https://smitstakepools.online",
  "pledge_address": "addr1s4hxkmsyl455gzt8npyjznnc72cd4nc363gjhjvayjd5nhnvegw2k3kz8nv"
}

 2  registry/ed25519_pk1de4kup8ad9zqjeucfys5u78jkrdv7yw52y4un8fyndyaumx2rj4ss5dkwm.sig 

@@ -1 +1 @@
ed25519_sig1lk739h6fkvh7rua2hajk0e0h9fh3jsad7zqxz4spkfpfd6e423dyju7j0r6cpvpx9rhuqfd3ctg2uckylmezw8xqmdja3ref6p93qpgdnsysc
ed25519_sig1dz0nd2g7lfunm2a6a33yzcg0y9h4dj06c2h7ae3hkyjht6kxdhmpg7qd26vf8vhaqz7atr5wr6ukptgjhrw7hek2470xzg455xxzzpgds4w0e

 

Could you please merge them into the master? The other files can be deleted.

 

Thank you in advance.

 

With kind regards,

Gertjan Smit

**Comment by admin-cf-2** [comment]
I'm sorry @Gertjan-stakingpoolholder it is mandatory that the automatic tests are passed. Like @sdalmeida said, they can't pass if you are changing more or less than two files. 

Every PR must consist of **exactly two** files.

**Comment by Gertjan-stakingpoolholder** [comment]
Hi,

 

What can I do to fix it?

 

Wit kind regards,

Gertjan

**Comment by admin-cf-2** [comment]
Simply split the PR into two.

**Comment by Gertjan-stakingpoolholder** [comment]
Was my other pullrequest to update BKIND successful?


Verstuurd vanaf mijn iPhone

**Comment by Gertjan-stakingpoolholder** [comment]
I do not know how to split it

**Pull request closed without merging**
