### PR TITLE
CAR10

### PR DESCRIPTION
**Pull request by akarthikeyan16**

### CODE REVIEW

**Comment by akarthikeyan16** [comment]
@admin-cf  Dear Admin, Its been more than 10days and am still awaiting for your approval.
Looking for your reply,
Thanks,
ADAStakingpools.com

**Comment by akarthikeyan16** [comment]
@admin-cf
Dear Admin,

I am still awaiting for your approval.
Any information will be highly appreciated.

Thanks,
ADAStakingpools.com

**Comment by admin-cf** [comment]
Apologies for the delay. Please see below

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pulls?q=is%3Amerged+is%3Apr+author%3Aakarthikeyan16+

We've noted that you have already registered 7 pools and want to continue registering more. Could you kindly elaborate on this so we can better understand your intentions? Please bear in mind that this is after all a Testnet and we do need to balance the needs of any one individual with those of the network as a whole.

**Comment by akarthikeyan16** [comment]
@admin-cf  Dear Admin,

My intention is to test the incentive scheme for the test-net Shelley delegation,staking and rewards mechanisms, fine tuning ITN versions within my pools , gaining user experience and marketing pools and bringing more people to experience staking rewards in our AWS\Google Cloud hosted pools.I am not going to register large no of pools as its not main-net and expensive running in AWS cloud platform for test-net pools running empty. My plan is to test maximum of 10 pools as trying in different OS and CPU/RAM different probabilities However I will not run all the pools instantly instead slowly will release the pools, once the current pools are over saturated,. I am registering this pool is to make sure not someone else registering before me and confuse the stakers.

Looking for your kind reply and appreciate your understanding.

Thanks,
Adastakingpools.com

**Pull request merged**
