### PR TITLE
ADLT1 - second PR

### PR DESCRIPTION
**Pull request by xdzurman**
VOIDING PR - https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/1854
I wanted to change pool fee - voided and created pool anew

### CODE REVIEW

**Comment by sdalmeida** [comment]
@xdzurman your PR only has 1 file (`ed25519_pk1sm9tturncddmavlg805jvnx24u6cxs5nwxtda06uw2sry5tgylrqjje9qd.sig`) 

You need to include `ed25519_pk1sm9tturncddmavlg805jvnx24u6cxs5nwxtda06uw2sry5tgylrqjje9qd.json` too

**Comment by xdzurman** [comment]
> @xdzurman your PR only has 1 file (`ed25519_pk1sm9tturncddmavlg805jvnx24u6cxs5nwxtda06uw2sry5tgylrqjje9qd.sig`)
> 
> You need to include `ed25519_pk1sm9tturncddmavlg805jvnx24u6cxs5nwxtda06uw2sry5tgylrqjje9qd.json` too

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/1854 VOIDED in previous, thats why

**Comment by sdalmeida** [comment]
I haven’t had to change the pool fee percentage before, so I don’t know if you need to void it or not.

**Comment by xdzurman** [comment]
@admin-cf-2 Yes, this was the process of voiding a pool and keep its ticker later. While the voiding PR was not yet merged, this PR did not have any changes compared to state of the repo, since repo had this json with ticker ADLT1, voiding PR changed it to VOID8, and this PR changed it back to ADLT1, therefore it didn't show and I just force-pushed nothing to reload this PR, now it shows the second file.

**Pull request merged**
