### PR TITLE
ELITE

### PR DESCRIPTION
**Pull request by Chaitanya-A**
Stake Pool Registry

### CODE REVIEW

**Comment by Chaitanya-A** [comment]
> Please note, url used are not in line with the Cardano Foundation’s trademark policy. https://cardanofoundation.org/en/legal/trademark-policy/ please contact [legal@cardanofoundation.org](mailto:legal@cardanofoundation.org) if you have further questions on this topic.

Changed my URL information and submitted.

**Comment by Chaitanya-A** [comment]
Its been 7 days, can u please approve this pull request ?

**Comment by admin-cf-2** [comment]
@Chaitanya-A it looks like your repo is configured in a way that it does not allow admin update to your fork. Our workflow requires you to allow us to make edits to your fork.
You need to check "allow edits from maintainers". This is in detail explained here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Chaitanya-A** [comment]
"Allow edit from maintainers" have been TICK Marked.

**Pull request merged**
