### PR TITLE
4YOU

### PR DESCRIPTION
**Pull request by SimonPucko**

### CODE REVIEW

**Comment by SimonPucko** [comment]
I have changed the stake pool name.

**Comment by SimonPucko** [comment]
I have changed my Pool URL and Staking Pool name. Nevertheless check fail.?

**Comment by admin-cf-1** [comment]
Click on details in the Checks pane and scroll to the bottom to find out why you're failing the automated checks..
("ERROR: Delta:  submissions must only affect files in 'registry' subdirectory" -> It looks like you're tweaking files but they are not at the right place!)

**Comment by SimonPucko** [comment]
I have changed my Pool URL and Staking Pool name and I added finally files to the appropriate directory. All Checks have passed finally.

**Pull request merged**
