### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by yoann54**

### CODE REVIEW

**Comment by yoann54** [comment]
Sorry for the mess in my commits i registered my pool with wrong adress i need to restart can u remove all my precedent commits ?

**Comment by yoann54** [comment]
this last commit 996c7fb is the good one thank you for your patience.

**Comment by admin-cf-1** [comment]
**Please note that the automated checks are failing.** Passing the automated tests is mandatory. To get more details about why it is failing, click on ‘details’ in the check section and scroll all the way down to the bottom of the resulting page.
(also suggest checking the Wiki for instructions on how to properly add to the registry)

**Comment by yoann54** [comment]
oh yes im a bit lost now because i have remove and add new .json .sig in the same pull request. Can u remove my commit or i should fork the registry and make a pull request with a new ticker ?

**Comment by admin-cf-1** [comment]
Look at what is tripping the automated check -current issue is you're touching 4 files - only supposed to ever touch 2 at a time. You could close this PR, and reopen a different one, or you can modify this one so it passes the checks.

**Comment by admin-cf-1** [comment]
Closing this PR because it is >7 days old or not relevant anymore. If you think this decision was wrong, please comment here so it can be reopened.

**Pull request closed without merging**
