### PR TITLE
KICK adding

### PR DESCRIPTION
**Pull request by lazyest**

### CODE REVIEW

**Comment by metuRiON** [comment]
Hi Admin, we are following KUNO Tickers layout :) I read the Legal section of the Wiki and can see that the url (homepage) and name comply. Please approve when ready, Thanks Kindly.

**Comment by metuRiON** [comment]
ahh, after re-reading https://cardanofoundation.org/en/legal/trademark-policy/ is the word ADA no longer allowed to be used within the description or name?

**Comment by metuRiON** [comment]
I'll remove the word ADA from it and then push the new commit

**Comment by admin-cf-1** [comment]
Thanks for your patience, merged in. Happy Staking!

**Pull request merged**
