### PR TITLE
CSP

### PR DESCRIPTION
**Pull request by A-Caccese**

### CODE REVIEW

**Comment by admin-cf-1** [comment]
Please note, name and url (homepage) used are not in line with the Cardano Foundation’s trademark policy. Please address those issues to avoid consequences. Refer to the following for details: https://cardanofoundation.org/en/legal/trademark-policy/
(suggest making the pool name more distinct/descriptive, and changing the URL to something more specific)

**Comment by A-Caccese** [comment]
> 
> 
> Please note, name and url (homepage) used are not in line with the Cardano Foundation’s trademark policy. Please address those issues to avoid consequences. Refer to the following for details: https://cardanofoundation.org/en/legal/trademark-policy/
> (suggest making the pool name more distinct/descriptive, and changing the URL to something more specific)

We have registered a new name: Capital Stake Pool (capitalstakepool.io). How can we proceed to update it?

Thanks.

**Comment by admin-cf-1** [comment]
(Wiki page : https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-do-I-delete-or-update-my-pool-metadata%3F)

> the procedure is the same as for registering new metadata:
> Update your JSON file
> Produce a new signature that will replace the existing one
> Submit a pull request

**Comment by admin-cf-1** [comment]
Greetings - thank you for updating the website to comply.

**Pull request merged**
