### PR TITLE
LOW

### PR DESCRIPTION
**Pull request by rausi**
Stakepool LowFeeStake

### CODE REVIEW

**Comment by admin-cf-2** [comment]
Closing this PR because I guess it’s no longer relevant.

**Comment by rausi** [comment]
?? Of course this is relevant. Please do not quess!!!

**Comment by admin-cf-2** [comment]
> ?? Of course this is relevant. Please do not quess!!!

Reopened. Please look into the failing checks. Thanks.

**Comment by rausi** [comment]
Now corrections are done :)

**Pull request merged**
