### PR TITLE
QIXX

### PR DESCRIPTION
**Pull request by phillewis**

### CODE REVIEW

**Comment by admin-cf-1** [comment]
**Please note that the automated checks are failing.** Passing the automated tests is mandatory. To get more details about why it is failing, click on ‘details’ in the check section and scroll all the way down to the bottom of the resulting page.
(signature validation issue?)

**Comment by phillewis** [comment]
Hi @admin-cf-1 

I am not quite sure what I need to change, as the sig file was generated by JCLI.

Is there any additional information that can be supplied regarding why validation failed?

Thanks

Phil

**Comment by admin-cf-1** [comment]
Hi Phil - unfortunately all I can see is that the fail seem to happen regarding the signature - please make sure you follow proper procedures to generate your signature - see https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-register-your-owner-metadata

**Comment by phillewis** [comment]
Thanks @admin-cf-1 

I have logged an issue for this at https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/987

**Pull request merged**
