### PR TITLE
ALOHA

### PR DESCRIPTION
**Pull request by cardanohawaiipool**
Please delete my currently merged (incorrect) ALOHA pool. Then please review this pull request and merge.

Thanks.

### CODE REVIEW

**Comment by cardanohawaiipool** [comment]
PR #645 will void ALOHA pool which was created in PR #199. 

This will be replaced by PR #520.

**Comment by admin-cf-2** [comment]
Closing this PR because I guess it’s no longer relevant.

**Comment by cardanohawaiipool** [comment]
Please reopen and merge this request.

I needed to remake my ticket, so I followed these directions:

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/641

The original PR#199 was incorrect, so I created this one, #520. However, because they have the same ticker, I had to use PR #645 to change the old ticker to VOID2. By doing this, it would allow current ticker and key of PR #520 to be merged.

Thanks. Sorry for any confusion.

**Comment by cardanohawaiipool** [comment]
Tagging @admin-cf-2 because I wasn't sure you would monitor closed requests.

**Comment by admin-cf-2** [comment]
I'm sorry but I can not open this pull request again, because you deleted the repo that submitted this pull request. @cardanohawaiipool

**Comment by cardanohawaiipool** [comment]
It is possible to just delete the files related to this closed pull request so I can resend a new PR?

**Comment by cardanohawaiipool** [comment]
Apologies, I will just send a PR to delete the json and sig files. Then submit another PR with the information again.

I think this is the best way to do it.

@admin-cf-2

**Comment by admin-cf-2** [comment]
> Apologies, I will just send a PR to delete the json and sig files. Then submit another PR with the information again.
> 
> I think this is the best way to do it.
> 
> @admin-cf-2

Okay thank you.

**Pull request closed without merging**
