### PR TITLE
CHEAP

### PR DESCRIPTION
**Pull request by cheapstaking**
updated json with description

### CODE REVIEW

**Comment by cheapstaking** [comment]
Just a description update if you could be so kind as to approve. We look a bit basic without a description in the wallet.

**Comment by admin-cf-2** [comment]
@cheapstaking  submissions must affect exactly two files (entry & signature), this one has 1

**Comment by cheapstaking** [comment]
> @cheapstaking submissions must affect exactly two files (entry & signature), this one has 1

I have no changes to by signature tho... Just need a description update to my existing json

**Comment by admin-cf-2** [comment]
@cheapstaking Please note, that you are signing your metadata, that means if you change your metadata the signature breaks. Therefore it is simply not possible to commit one file. Hope, that makes sense.

**Comment by admin-cf-1** [comment]
Closing this PR because it appears to not be relevant anymore. If you think this decision was wrong, please comment here so it can be reopened.

**Pull request closed without merging**
