### PR TITLE
Change owner_addr and owner_pub for PUDIM

### PR DESCRIPTION
**Pull request by Aranad**
Change owner_addr and owner_pub for PUDIM (original PUDIM is now VOID3)

### CODE REVIEW

**Comment by Aranad** [comment]
Sorry for so many PR's and openings and closings, I've been trying to request a pub_key change without the automatic checks failing, but can't figure it out :-(

**Comment by admin-cf-1** [comment]
Do the voiding as one PR, then the new registration as a separate PR. See Wiki for details.

**Comment by Aranad** [comment]
@admin-cf-1 I did the void PR [#1066], and then did another commit with the new files, but couldn't do a PR for that, but it's combined the second commit into the first PR...! Are you able to merge that?

**Comment by admin-cf-1** [comment]
I'm afraid you will have to do two separate PRs for consistency - thanks for understanding

**Comment by Aranad** [comment]
@admin-cf-1  I don't know how to do it, so for now I've just updated the PR to only do the voiding of PUDIM, so all checks are passing now, could you merge that? I can then do another PR for the new files later. Thanks :-)

**Comment by Aranad** [comment]
@admin-cf-1 Ok I think I finally got it right! I figured out how to make multiple PR's so now there's [#1066] which tests pass for properly to void PUDIM, and then [#1069] which updates the details and only has the error of "duplicate ticker" like the procedure says :-)

**Pull request closed without merging**
