### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by blueclearsky**

### CODE REVIEW

**Comment by admin-cf-2** [comment]
@blueclearsky I'm sorry PR does not complete the automatic checks, because your TICKER name is not valid. 

Error message: Not an uppercase ASCII of length 3 to 5: Blue

**Comment by blueclearsky** [comment]
> @blueclearsky I'm sorry PR does not complete the automatic checks, because your TICKER name is not valid.
> 
> Error message: Not an uppercase ASCII of length 3 to 5: Blue

what must i do to fix it

**Comment by KtorZ** [comment]
@blueclearsky 
You have to change your ticker to be a 3-5-character string made of uppercase letters. 
For example: "BLUE" instead of "Blue".

**Comment by blueclearsky** [comment]
> @blueclearsky
> You have to change your ticker to be a 3-5-character string made of uppercase letters.
> For example: "BLUE" instead of "Blue".

thank you very much. can you tell me the write way to do this.  must i eddit the file and upload it again. or is there a way to edit the file?

**Comment by blueclearsky** [comment]
thank you very much. can you tell me the write way to do this. must i eddit
the file and upload it again. or is there a way to edit the file?

Op za 18 jan. 2020 om 16:38 schreef Matthias Benkort <
notifications@github.com>:

**Comment by admin-cf-2** [comment]
@blueclearsky You can't simply edit the json file because then your signature file breaks. Please stick to the progress when generated the first file.

**Comment by blueclearsky** [comment]
oke thank you i al ready edit the file so that was not good. so i must
idelet the files and upload the new one. i go to try that

Op za 18 jan. 2020 om 18:55 schreef Cardano Foundation Team <
notifications@github.com>:

**Comment by blueclearsky** [comment]
i have upload the new files is it good now?

Op za 18 jan. 2020 om 19:08 schreef Blue Sky <blueskystakepool@gmail.com>:

**Comment by admin-cf-1** [comment]
**Please note that the automated checks are failing.** Passing the automated tests is mandatory. To get more details about why it is failing, click on ‘details’ in the check section and scroll all the way down to the bottom of the resulting page.
(-> _submissions must only affect files in 'registry' subdirectory_: The files you commit must be inside /registry/ ! right now they are at the root on the structure)

**Comment by blueclearsky** [comment]
thank you, i am all new to this my pool is runnig good and now the last
step wont work. can you please explain what i must do . in my system i see
the files in incentivized-testnet-stakepool-registry/registry

Op zo 19 jan. 2020 om 07:23 schreef Cardano Foundation Team <
notifications@github.com>:

**Comment by blueclearsky** [comment]
thank you,
i think its oke now but Merging can be performed automatically with 1
approving review.

Op zo 19 jan. 2020 om 10:41 schreef Blue Sky <blueskystakepool@gmail.com>:

**Pull request merged**
