### PR TITLE
SBN

### PR DESCRIPTION
**Pull request by magicturtle01**
Please add this pool to the registry.

### CODE REVIEW

**Comment by magicturtle01** [comment]
I have tried to open a new one, but the box for checking that is missing.

**Comment by magicturtle01** [comment]
> It looks like your repo is configured in a way that it does not allow admin update to your fork. Our workflow requires you to allow us to make edits to your fork.
> You need to check "allow edits from maintainers". This is explained in detail [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

I have tried to open an new one, but the box for checking that is missing.

**Comment by skokasik** [comment]
> > It looks like your repo is configured in a way that it does not allow admin update to your fork. Our workflow requires you to allow us to make edits to your fork.
> > You need to check "allow edits from maintainers". This is explained in detail [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
> 
> I have tried to open an new one, but the box for checking that is missing.

Hey Magicturtle01, i was actually in the same boat as you. I didn't see the checkbox option yesterday. but the option appears to be avaialble this morning if you open your PR again. It should be on the right hand side.

**Comment by magicturtle01** [comment]
> > > It looks like your repo is configured in a way that it does not allow admin update to your fork. Our workflow requires you to allow us to make edits to your fork.
> > > You need to check "allow edits from maintainers". This is explained in detail [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
> > 
> > 
> > I have tried to open an new one, but the box for checking that is missing.
> 
> Hey Magicturtle01, i was actually in the same boat as you. I didn't see the checkbox option yesterday. but the option appears to be avaialble this morning if you open your PR again. It should be on the right hand side.

Thanks, it did work.

**Comment by magicturtle01** [comment]
Thanks so far. But it seems now that there are three SBN pools visible in Daedalus rewards. Probably my mistake, because they have all the same info/ are from me... but how do I fix it?

**Comment by admin-cf-2** [comment]
@magicturtle01 Please see https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/Why-is-my-pool-listed-multiple-times-in-Daedalus%3F

**Comment by magicturtle01** [comment]
> @magicturtle01 Please see https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/Why-is-my-pool-listed-multiple-times-in-Daedalus%3F

So, as I understand it, there is at the moment nothing I can do.

**Comment by admin-cf-2** [comment]
@magicturtle01 
You have to "void" the metadata that you no longer want to appear like described here: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-do-I-delete-or-update-my-pool-metadata%3F

**Comment by magicturtle01** [comment]
Thanks so far. 
The pool with the ID 
a15313c834f90c7fcea8eef4d9a6653b762a1f86f2efd44dd488aace4c9c2619
is the one that should continue to be in the registry.
But all of the SBN pools have the same Metadata. 
So how do I specify in the json which pool to delete?

**Pull request merged**
