### PR TITLE
cardanoist information will be updated

### PR DESCRIPTION
**Pull request by utkusonmez**
your pull requests only get 2 files changeable. So I have to delete files first.

### CODE REVIEW

**Comment by utkusonmez** [comment]
@admin-cf-1 please check this pr, I have to delete these files to add new ones.

**Comment by KtorZ** [comment]
Please have a look at: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/641

We cannot delete files from the registry directly. If you could delete these files, anyone could!

**Comment by utkusonmez** [comment]
@KtorZ I know but I added these files. You can check that pr. What happens, if I add new files without deleting existing ones?

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/872

**Comment by KtorZ** [comment]
Hi @utkusonmez !

Did you look into [FAQ: How do I update / delete my metadata in the registry #641](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/641) I linked above? 

If something isn't clear in this document, I'd rather update it rather than giving you an ad-hoc answer!

**Pull request closed without merging**
