### PR TITLE
AUH

### PR DESCRIPTION
**Pull request by redgoatpioneers**

### CODE REVIEW

**Comment by redgoatpioneers** [comment]
@admin-cf-1 it looks like signature verification is failing, but everything looks correct on my end:

Verify public key can be regenerated using private key:
```
./jcli key to-public --input ./owner.prv
ed25519_pk1kyvyhs30vx9denlwygdua20f3et6ee2d07rjz8g8xatkajknctrs2g93ha
```

Generate sig of registration JSON file using same private key:
`./jcli key sign --secret-key owner.prv --output ./incentivized-testnet-stakepool-registry/registry/ed25519_pk1kyvyhs30vx9denlwygdua20f3et6ee2d07rjz8g8xatkajknctrs2g93ha.sig ./incentivized-testnet-stakepool-registry/registry/ed25519_pk1kyvyhs30vx9denlwygdua20f3et6ee2d07rjz8g8xatkajknctrs2g93ha.json`

Verify the signature using the private key:
```
./jcli key verify --public-key ./owner.pub --signature ./incentivized-testnet-stakepool-registry/registry/ed25519_pk1kyvyhs30vx9denlwygdua20f3et6ee2d07rjz8g8xatkajknctrs2g93ha.sig ./incentivized-testnet-stakepool-registry/registry/ed25519_pk1kyvyhs30vx9denlwygdua20f3et6ee2d07rjz8g8xatkajknctrs2g93ha.json
Success
```

In the buildkite/nix verification scripts, is there a check happening that I can verify locally and maybe pinpoint what's bothering it?

**Comment by admin-cf-1** [comment]
I do not have direct access to the tests themselves - are you using the same keys that you registered the pool onchain with? I can only point you back to the wiki - Also consider asking in the Shelley Telegram channel - much help to be had there

**Comment by redgoatpioneers** [comment]
Yep. I tried creating a new stake pool and address to repeat the steps and make sure I follow them correctly. I used the createStakePool.sh script referenced at https://iohk.zendesk.com/hc/en-us/articles/900000032403, and used that owner account to create the stake pool certificate. Then I used the public key as the owner and file name for this registration, and signed the file using the private key from that same script. Still failed, not sure what to do at this point. Am I missing a step? Everything seems ok after looking at other successful pull requests.

**Comment by redgoatpioneers** [comment]
Yep. I tried creating a new stake pool and address to repeat the steps and make sure I follow them correctly. I used the createAddress.sh script referenced at https://iohk.zendesk.com/hc/en-us/articles/900000032403, and used that owner account to create the stake pool certificate. Then I used the public key as the owner and file name for this registration, and signed the file using the private key from that same script. Still failed, not sure what to do at this point. Am I missing a step? Everything seems ok after looking at other successful pull requests.

These are the two nodes I have certified using this most recent public key:
- 2da09bc2dc076ef38040a738615a73c25bff1f2a0542ef587d8cf60654e231c7
- 156505260c565fd6f54cb96d9886bd48904e1b8dc57d0e7b866b7ac70a1ca3ca

**Comment by admin-cf-1** [comment]
I can only tell you that the current step is failing unfortunately - I suggest asking for help in the [telegram group](https://t.me/CardanoStakePoolWorkgroup) which has most operators in it.. There are a few guides out there you might want to check your steps against - and although out of the 500+ pools submitted, a few (<5%)  seem to have issue with the signature part more than anything... Thanks for pinging what the issue is if feasible, would love to have a ready made answer to point ppl to!

**Comment by admin-cf-1** [comment]
Closing this PR because it is >7 days old or not relevant anymore. If you think this decision was wrong, please comment here so it can be reopened.

**Pull request closed without merging**
