### PR TITLE
HROI1

### PR DESCRIPTION
**Pull request by moomanchoo**

### CODE REVIEW

**Comment by sdalmeida** [comment]
hum... this is an interesting error. Its complaining that your `owner` key has invalid chars
image

But looking at what you submitted, everything looks fine. @admin-cf might have to review this and provide some feedback, as I don't even know what this issue can be.

**Comment by moomanchoo** [comment]
Hi Simon

At first I thought I might have used the wrong key as the exact names are
different from the process when the iohk videos were made.

I did copy this code by hand and I've just noticed the the 1 and L in this
font look exactly the same. So maybe one or both of those are wrong. I've
checked it multiple times and I cant see another possibility. Is the pk1
always pk1 or pkL?

Steve

**Comment by sdalmeida** [comment]
Ah! Found the issue.

You key and file name is wrong. You have `pkl` instead of `pk1`

Change your key and file name to `pk1`, sign it and it should pass.

**Comment by moomanchoo** [comment]
Great and if that doesnt works I'll change the second 1/L too. I belive
that's a 1 currently.

Cheers.

**Comment by moomanchoo** [comment]
Happened again. Now I dont know what is going on. Shall i try the second
1/L swap?

**Pull request closed without merging**
