### PR TITLE
update url

### PR DESCRIPTION
**Pull request by zyanki**
I updated url to solve #1047. https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/1047

### CODE REVIEW

**Comment by admin-cf-1** [comment]
Please note, after legal review, URL (homepage) used is not in line with the Cardano Foundation’s trademark policy. Refer to the following for details: https://cardanofoundation.org/en/legal/trademark-policy/  Please address the issue to avoid consequences. (suggest using a less generic URL, or even **reverting to the Facebook URL** you were using before).
Thank you for your help!

**Comment by zyanki** [comment]
Are saying about current url or previous url?

**Comment by zyanki** [comment]
Are you saying about current url or previous url?

**Comment by admin-cf-1** [comment]
"**https://stakepoolada.net**" does not pass legal review (see https://cardanofoundation.org/en/legal/trademark-policy/)
BUT 
**https://www.facebook.com/Cardano-Stake-pool-HCMC-109845963856090/**
is ok if you want to use that one instead.

**Comment by zyanki** [comment]
I do not understand. what you are saying is that Word trademarks include ADA so stakepoolada isn't legal. right? but how does "cardanoz" pass your review?
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/213/commits/318b82e18b398c58923a71942cd4ce97dfb389a7

**Comment by zyanki** [comment]
Im gonna do it this week

**Pull request merged**
