### PR TITLE
1PCTA

### PR DESCRIPTION
**Pull request by 1procentpool**

### CODE REVIEW

**Comment by tobiasley** [comment]
Could you please have a look at this PR? Eagerly waiting :)

**Comment by 1procentpool** [comment]
Would you please take a look at this one? Thanks

**Comment by 1procentpool** [comment]
@admin-cf-1 Am I being censored now? It seems like you have merged many PRs that came after mine. Please let me know if this is intentional censorship or just an oversight. Thanks!

**Comment by admin-cf-1** [comment]
The applications are being reviewed and are taking a bit longer due to internal considerations. We've noted that you already registered 11 pools and want to register 25 more. Could you kindly elaborate on this so we can better understand your intentions? Please bear in mind that this is after all a Testnet and we do need to balance the needs of any one individual with those of the network as a whole.

**Comment by 1procentpool** [comment]
I completely understand. My intention is to test the incentive scheme for the testnet, and hence act according to my own best interests. This will give IOHK the best data to act upon, and tweak the scheme and protocol as needed. I did hesitate to create these additional pools, since taking too much stake away from other good actors could potentially discourage them. But then again, if this happens under the current testnet setup, IOHK needs to know about it and fix it.

I have the best intentions for Cardano at heart, and I want Cardano to have the best possible protocol. We get there by testing the limits of the system - not by trying to moderate to avoid the rough edges. The car needs to fail in the crashtest, before it gets on the road.

Another consideration was copy cats. I see that you have allowed 2 Percent Pool to copy all my descriptions and name scheme, and also 1PCOM, which has taken www.1percentpool.com as domain. So you're not moderating for people trying to steal or copy succesful players. It's your choice not to do so, and I'm completely fine with it, as long as it's an active choice. For this reason, I foresee that someone else would very soon start creating 1PCTA, 1PCTB and so and, and confuse the stakers. That's why I've registered all the variations.

To be clear, I do not intend to run 25 more pools instantly. This would be a bad strategy. I would however slowly roll them out, as long as the currently pools are over saturated, and slowly fill them up. If the stakers decide that this is centralisation and bad for the system, they will not stake with the 1PCT pools. If they however do not care, and the staking and opening of new pools continues, IOHK knows that they need to change the system to disincentivize the behaviour.

Also, people are free to delegate to whoever they like. There is no certainty that people will even delegate to the new pools.

**Comment by 1procentpool** [comment]
@admin-cf-1 It's been 10 days now. We're still waiting for your decision here, and we know the community is following your decision as well.

Do you plan to be a centralised authority on registering stake pools in Daedalus and Yoroi? This goes against everything that Cardano stands for. A **censorship resistant** distributed ledger. Will you also start revoking tickers if pools don't behave as you want them to? Where does this end?

It is a slippery slope when you start censoring like this. It's not like you can prevent us from opening more pools, you can only make it less transparent to the community by using the very thing that we're trying to prevent; censorship!

**Lets examine the options here:**
**-**We could play the cat-and-mouse game, and start opening new pools under new names, hiding the true affiliation between the pools. We're trying to be transparent with the community by using the same name for all pools. Please let us be transparent!
**-**We could simply register more pools under the existing tickers. We could have 100 pools under a single ticker, but this defeats the whole idea of having tickers. We already started doing this before your first comment, but we really do not want to go further down this road. It's hurting the user experience a lot, and unique tickers is the best option for everyone. Don't make us have to go down this road.
**-**We could cry wolf to all the troll crypto reporters out there, telling them how this great censorship resistant protocol is in fact being censored by the Cardano Foundation, who can pick and choose who gets to run a stake pool. Having Cardano compared to EOS is not what we want. 

Having the Cardano Foundation censoring stake pools and getting publicity about this, is one of the most devastating things that could happen right now. This is NOT a threat; this is a legit concern and a consequence of your actions. We would never start a negative campaign about Cardano, since we love the protocol and have large holdings of ADA. We want it to thrive, and become everything that IOHK, Cardano Foundation and Emurgo envision it to be. That being said, it is only a matter of time before someone else, with bad intentions, dig out this message thread and starts writing sensationalistic articles about how Cardano is broken and censored. The community is already following this thread and waiting for your decision.

We fully understand your hesitation on this matter, but we urge you to do the responsible thing here, and not try to censor the stake pool ticker registrations. It's a lost cause anyways, since all you can do is make it less transparent for the users who run the pools, and make it a worse user experience. If our behaviour needs changing, it should be done on the protocol level - not by having a centralised authority deciding who gets to run a stake pool.

**Comment by admin-cf** [comment]
The Shelley Incentivized testnet is intended to test specific aspects of the Shelley delegation, staking and rewards mechanisms, and is not feature-complete compared to the full implementation that is planned for mainnet. We have been very encouraged by the positive community response to the testnet, and by the many staking businesses that are being developed.

At this stage of testnet development, however, many of the features that are being developed at a protocol level for the Shelley mainnet need to be implemented off-chain or via manual workarounds. Stake pool metadata registration is one of these, currently being managed by the Cardano Foundation. Any pool operator is still able to register their pool on chain and to promote it their pool independently, if they wish to do so.

In order to manage the security and robustness of the Incentivised testnet  as a whole (including risk of sybil attacks and other adversarial behaviours), we do not encourage operators to register large numbers of pools at this stage. This also helps drive decentralisation by encouraging participation to be as broad and balanced as possible. We do assess each ticker request as it comes in and flag any that are clearly trying to imitate existing tickers. We will continue to reach out to operators requesting large numbers of registrations and will work with them to understand and accommodate their needs while ensuring the sustainability of the testnet. Registrations won’t be unreasonably withheld but we do appreciate your support and patience during this testnet phase.

**Comment by 1procentpool** [comment]
Thank you so much for the detailed answer. Much appreciated.

Please know that the intention behind starting 1 Percent Pool was to test the game theory of the system. I have very high hopes for Cardano, but the things that I have always doubted the most, was the ability to defend against sybil attacks on the network.

For this reason, I set out to imitate what an attacker would do - take a very low fee and run a lot of pools. The whole idea of a testnet is to test if things will work as expected, and since sybil attacks in my eyes is the largest risk for the Cardano project, this was vital to test out. If it would be too easy to gain a lot of stake in the network, we have to implement more advanced strategies for defending against it. Otherwise, sybil attacks will happen and the trust in Cardano will be deeply hurt, and maybe even becomes worthless.

I fully buy into your arguments about this not being a full testnet yet. It is not yet feature complete, and it does not make sense to test the sybil attacks in depth yet. It's a completely valid point. I also deeply recognise that one of the defences against sybil attacks, is attracting a large number of passionate and dedicated stake pool operators, so the total stake will be spread out among a larger number of pools. This will make sybil attacks much harder to achieve.

For those reasons, I have decided to stop the test. I will not open any new 1PCT pools, or try to gain more stake. Once retirement certificates and maintenance certificates becomes available, I will close down the new pools I've opened recently, and add a fee to the 1PCT pools that are left. This will make it easier for other pools to gain stake, and will contribute to a more healthy community.

Please ensure that there will be a heavy focus around sybil attacks, and what we need to do to defend against them. I think this test vividly showed that we need to think more about the issue. This is the center pillar that the whole protocol depends on!

**Comment by rjmcoin** [comment]
I agree with 1procentpool and find their actions appropriate in every way, including their voluntary agreement to stop opening new pools.

The testnet was set up without social parameters, but even if it was, this project must rely on protocol design. I would encourage more significant methods of testing in the future if possible.

I also agree with the Cardano Foundation's verbal request to reduce this activity in order to flush out other details of the testnet protocols at this time. On 1procentpool's good nature, they have verbally agreed but it's clear that all the parameters around stake pool registration and operation need serious attention.

**Comment by ilap** [comment]
> Do you plan to be a centralised authority on registering stake pools in Daedalus and Yoroi? This goes against everything that Cardano stands for. A **censorship resistant** distributed ledger. Will you also start revoking tickers if pools don't behave as you want them to? Where does this end?

Nope, they're just try to eliminate a kind-of Sybil attack on the ITN, in which, on purpose, they did not apply the punishment described in the paper and the __high fee, pledge__ combo in the reward calculation, which would eliminate it. 

So, you can play here and know, cos you won't be able to do the same on mainnet, as it does not matter that you will go down to 0.00001% TAX your pool won't be attracted, if you would do not be able to pay that high fees (for mainnet, based on the paper, I calculated around 3m pledge) for all your nodes.

The 2nd, it does not matter whatever bullshits you wrap in your request, the ppl who have some common sense can see you through. But, the others, well..., unfortunately,  we cannot save them.:)

**Comment by PegasusPool** [comment]
@1procentpool Do you want to help the network and the project succeed? Why are you not sharing your setup and experience with others? Hundreds of people on telegram help each other out to configure and fine tune their pools. I'm sure many people would benefit from you sharing your experience on the testnet. I invite you to join https://t.me/CardanoStakePoolWorkgroup and share your knowledge with others.

**Comment by 1procentpool** [comment]
@PegasusPool I'd love to help! Believe it or not, but you are the first stake pool to ask about our experience and setup. There is a contact form on the website, but no one reached out.

I have been watching the Telegram group from time to time, but I've been pushed away by toxic behaviour from other pool operators. Instead of asking for help, I've been actively attacked by groups of operators trying to 'kick our pools off the network'. I'm not sure why Sandstone Pool opted for the offensive strategy, but that behaviour doesn't invite to a helpful dialog. All they had to do was write an email.

Since you politely ask and invite me to be active in the group, I will share the details of the architecture and node setup that makes 1 Percent Pool succesful and fully automated. All the scripts are very tailored to 1 Percent Pool currently, so it will take a bit of time to make them generic so everyone can benefit from them. But we'll get there.

I'll be writing a full guide about how to stabilize and automate the setup, and share it with the group. My hope is that the aggressive pool operators will stop their attacks, and also invite to a healthy dialog.

The full guide will be posted in the telegram channel within a few days, and the scripts will be put in our Github repository.

Looking forward to a healthy community collaboration!

**Comment by PegasusPool** [comment]
Thank you @1procentpool. I'm looking forward to read about the setup and configuration of your pools and the collaboration with other pool operators!

**Comment by 1procentpool** [comment]
@PegasusPool The guide for how the pools are being run have been created at the website now: https://www.1percentpool.eu/the-1percentpool-guide-to-a-worry-free-stake-pool-operation/

I have a very busy week ahead of me, so I hope this guide will get the community started. I will elaborate on it later, and join the Telegram channel actively once I get a proper Telegram account set up.

Once all stake pool operators get their own private bootstrap clusters set up (see guide), we should also see an improvement in the wallet performance, with fewer timeouts and errors, since the 1000 pools won't hammer the IOHK bootstrap/wallet peers as hard.

To the community, with love, from 1PercentPool.

**Pull request closed without merging**
