### PR TITLE
NOVA

### PR DESCRIPTION
**Pull request by tushjd**

### CODE REVIEW

**Comment by tushjd** [comment]
why did buildkite failed?

**Comment by RickyyValdez** [comment]
> why did buildkite failed?

I believe that's normal. It has to be run by an admin.

**Comment by tushjd** [comment]
my first try was denied because of wrong website. but the buildkite test passed just a few seconds after creating the pull request. this time it took a day and failed.

**Comment by tushjd** [comment]
OK I found it. Its a missing " in the pool name. 
@RickyyValdez your check has failed because of a wrong signification

**Comment by RickyyValdez** [comment]
> OK I found it. Its a missing " in the pool name.
> @RickyyValdez your check has failed because of a wrong signification

I'm really rusty. This is my first Pool ever. Im guessing the .sig file correct ?

**Comment by tushjd** [comment]
Yes its the .sig file I guess. You have to sign it with your owner private key

**Comment by RickyyValdez** [comment]
> Yes its the .sig file I guess. You have to sign it with your owner private key (repeat after each change)

@tushjd Thank you for that info. Ill try it again.

**Pull request merged**
