### PR TITLE
VOID 1LOVE

### PR DESCRIPTION
**Pull request by usrbinsam**
- Renamed ticker to VOID69
- Submitting new signature

PR #651 is the original registration we're voiding here.

### CODE REVIEW

**Comment by usrbinsam** [comment]
CI is failing "validate", not sure why? JSON file appears to be perfectly valid.

**Comment by usrbinsam** [comment]
Hold on I'm an idiot, one sec...

**Comment by usrbinsam** [comment]
Alright so now that I'm understanding the issue, the owner lost the private key that was used to register #651. Am I correct in assuming that means he's forever lost that ticker and needs to just start registration over with a new ticker name?

**Comment by admin-cf-2** [comment]
> Alright so now that I'm understanding the issue, the owner lost the private key that was used to register #651. Am I correct in assuming that means he's forever lost that ticker and needs to just start registration over with a new ticker name?

Sorry to hear that, your assumption is right.

**Comment by usrbinsam** [comment]
Closing - cannot merge.

**Pull request closed without merging**
