### PR TITLE
EVER

### PR DESCRIPTION
**Pull request by keynobase**
I've changed the web page for other

### CODE REVIEW

**Comment by admin-cf-1** [comment]
conflicts - please address, and consider resubmitting.

**Comment by keynobase** [comment]
Hello,

I have changed my URL website.

Whats the trouble ?

Regards,

**Comment by keynobase** [comment]
> conflicts - please address, and consider resubmitting.
I have changed my URL website.
Whats the trouble ?

**Comment by admin-cf-1** [comment]
It looks like you are trying to merge from a side branch (you have 2 branches with different code creating conflicts) - please make sure you resolve your own conflicts, suggest you only work from a single master branch.

**Comment by keynobase** [comment]
Now I only has one branch, I don know how solve it

**Pull request closed without merging**
