### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by wdy43di**
Submitting DRCH or Drachma staking pool.

### CODE REVIEW

**Comment by admin-cf-2** [comment]
@wdy43di submissions must affect exactly two files (entry & signature), this one has 4

**Comment by wdy43di** [comment]
I have deleted the first set of submissions.  I apologize I have
struggled and learned quite a bit about github with this. I am
normally just a networking guy.

Thank you for your service,

John

**Comment by admin-cf-1** [comment]
Hey John - welcome and looking forward to your Staking Pool entry! 
Note: **Please note that the automated checks are failing.** Passing the automated tests is mandatory. To get more details about why it is failing, click on ‘details’ in the check section and scroll all the way down to the bottom of the resulting page.
(it looks like you're using http and need https..)

**Comment by wdy43di** [comment]
Cardano,

What is failing?  drachma.tech, or something else?

**Comment by wdy43di** [comment]
Talked to Chris Graffagnino and he pointed out my submission lists
http://drachma.tech and i need to switch it to https://drachma.tech so i
will be working on that

**Comment by admin-cf-1** [comment]
Hi John - thanks for completing the PR process, you're nearly there :)

**Comment by wdy43di** [comment]
Sir,

What am I missing at this point?

**Comment by wdy43di** [comment]
Someone pointed out that I posted my private key on github.. so ill be
starting over

**Comment by admin-cf-1** [comment]
Closing this PR because it appears to not be relevant anymore. If you think this decision was wrong, please comment here so it can be reopened.

**Pull request closed without merging**
