### PR TITLE
Delete ed25519_pk146xzu8vp7rdl9kxmgzxldy2t08lu23c96cl7hv539qrzckvs02v…

### PR DESCRIPTION
**Pull request by welshes99**
…q2yshlf.sig

### CODE REVIEW

**Comment by sdalmeida** [comment]
@welshes99 Why did you create 2 PR's to delete the .sig and .json? Why not put both files in 1 PR?

**Comment by moomanchoo** [comment]
Sorry these two commits are a mistake. First time using Github. Only the HIROI commit is valid.

**Comment by moomanchoo** [comment]
Lol. Woops wasn't me . I thought I did something similar. Never mind that was local.

**Comment by welshes99** [comment]
I had 2 old files that I wanted to remove and replace with new ones, 1 json
and 1 sign added earlier today us cst.

Hopefully you see two files with a timestamp of today anything older under
"KAIRO" can be deleted still learning how GitHub works from Linux
terminal..so maybe I messed it up?

**Comment by admin-cf-2** [comment]
Closing this PR because I guess it’s no longer relevant. If you think this decision was wrong, please comment it here so it can be reopened.

**Pull request closed without merging**
