### PR TITLE
ARTIS stake pool

### PR DESCRIPTION
**Pull request by bohenicus**

### CODE REVIEW

**Comment by bohenicus** [comment]
why my previous request was closed?
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/591

**Comment by bohenicus** [comment]
seems that my previous commit was discarded without motive

**Comment by admin-cf-2** [comment]
> why my previous request was closed?
> #591

Because it did not pass the automatic checks and this was not addressed. I can open it again if you like. btw this one does also not pass the automatic checks.

Errors:
  | Submission content:
  | Error in $.homepage: Not an https URI: http://artis.qajek.net

**Comment by bohenicus** [comment]
there is homepage (draft of the final version now - but is responding):
http://artis.qajek.net/

So the problem is with http**s** (now is not secure access) ? Or something other ?

**Comment by bohenicus** [comment]
Now I switch webpage http://artis.qajek.net to handle also SSL access. I hope that will help.

**Comment by bohenicus** [comment]
shouldn't I see already the name of mine stake pool in master registry page ?
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/tree/master/registry

There is still no ARTIS entry.

**Comment by admin-cf-2** [comment]
It's in for sure, to me it sounds like you are looking at the commit names. You named the commit "adding https access".

**Pull request merged**
